Description: >
  Chris Iregbu - Udagram Project
  
  This template deploys a stack with IAM role that will use to upload/download files from an S3 bucket

Parameters:
  EnvironmentName:
    Description: An environment name that will be prefixed to resource names
    Type: String
  
Resources:

  UdagramIAMRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${EnvironmentName}-Udagram-Role"
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - ec2.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: "/"

  UdagramPolicies:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub "${EnvironmentName}-Udagram-Policies"
      PolicyDocument:
        Statement:
        - Effect: Allow
          Action: 
          - "ec2:DescribeAddresses"
          - "ec2:AllocateAddress"
          - "ec2:DescribeInstances"
          - "ec2:AssociateAddress"
          - "ssm:Get*"
          - "s3:Get*"
          Resource: '*'
      Roles:
      - !Ref UdagramIAMRole
      
  UdagramInstanceProfile:
    Type: "AWS::IAM::InstanceProfile"
    Properties:
      Path: "/"
      Roles:
      - !Ref UdagramIAMRole

Outputs: 
  UdagramRole:
    Description: Udagram Role
    Value: !Ref UdagramIAMRole
    Export:
      Name: !Sub ${EnvironmentName}-UdagramRole

  InstanceProfile:
    Description: Instance profile for Udagram Role
    Value: !Ref UdagramInstanceProfile
    Export:
      Name: !Sub ${EnvironmentName}-InstanceProfile
